Revert "op3: Build SnapdragonGallery"
Keeps crashing on editing a picture:

java.lang.UnsatisfiedLinkError: No implementation found for long com.thundersoft.hz.selfprotrait.detect.FaceDetect.native_create()

This reverts commit ded1ab1573bdd76bf0d2e317d3e44229466944ed.