Revert "Disable librecovery_updater_msm"
This fixes the following error:
KeyError: "There is no item named 'RADIO/tz.mbn.bak' in the archive"

The releasetools.py in device/qcom/common is needed to resolve .bak
files for radio filesmap.

This reverts commit 3f5e9f960fe834dcb688d07460913d60329bbbbd.